name: Deploy to GCP

on:
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. SSH into the GCP VM and deploy
    - name: Deploy to GCP VM
      uses: appleboy/ssh-action@v0.1.12
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/George-Emad/cicd/Traefic-With-FastAPI-Containerized-Project-
          git pull origin main
          docker compose down
          docker compose -f docker-compose.traefik.yml down 
          docker compose up -d --build
          docker compose -f docker-compose.traefik.yml up
